name: MLOps Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python train_model.py

      - name: Show model metrics
        run: cat model/metrics.json

      # Build the Docker image after the model has been retrained successfully:
      # Updated to v3 because docker/login-action@v1 showed a deprecation warning.
      # GitHub Actions warning stated actions will use Node.js 24 by default from 02/06/2026.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build Docker image with Docker Hub repository name
      - name: Build Docker image for Docker Hub
        run: docker build -t thelastmcguire/coaching-block-api:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push thelastmcguire/coaching-block-api:latest
