name: MLOps Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python train_model.py

      - name: Show model metrics
        run: cat model/metrics.json
